import React from 'react';
import { View, Text, StyleSheet, TouchableOpacity } from 'react-native';
import * as Print from 'expo-print';
import { useLocalSearchParams, router } from 'expo-router';
import { formatINR } from '../../src/utils/currency';

export default function ReceiptModal() {
  const params = useLocalSearchParams<{ id?: string; amount?: string }>();
  const amount = Number(params.amount ?? 0) || 0;

  return (
    <View style={styles.container}>
      <View style={styles.card}>
        <Text style={styles.title}>Receipt</Text>
        <Text style={styles.row}>Order ID: <Text style={styles.value}>{params.id ?? 'N/A'}</Text></Text>
        <Text style={styles.row}>Amount: <Text style={styles.value}>{formatINR(amount)}</Text></Text>
        <TouchableOpacity
          accessibilityRole="button"
          accessibilityHint="Export receipt as PDF"
          style={[styles.closeBtn, { backgroundColor: '#10B981' }]}
          onPress={async () => {
            const html = `<!doctype html><html><body><h1>Receipt</h1><p>Order ID: ${params.id ?? 'N/A'}</p><p>Amount: ${require('../../src/utils/currency').formatINR(amount)}</p><p>Generated by TAPANGO</p></body></html>`;
            try { await Print.printAsync({ html }); } catch {}
          }}
        >
          <Text style={styles.closeText}>Export PDF</Text>
        </TouchableOpacity>

        <TouchableOpacity accessibilityRole="button" accessibilityHint="Close receipt" onPress={() => router.back()} style={[styles.closeBtn, { marginTop: 8 }] }>
          <Text style={styles.closeText}>Close</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', alignItems: 'center', justifyContent: 'center', padding: 16 },
  card: { backgroundColor: '#fff', borderRadius: 12, padding: 20, width: '100%' },
  title: { fontSize: 18, fontWeight: '800', marginBottom: 12 },
  row: { fontSize: 16, color: '#374151', marginTop: 4 },
  value: { fontWeight: '700', color: '#111827' },
  note: { color: '#6B7280' },
  closeBtn: { marginTop: 16, paddingVertical: 12, borderRadius: 8, backgroundColor: '#007AFF', alignItems: 'center' },
  closeText: { color: '#fff', fontWeight: '700' },
});
