name: Harden Supabase for production

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

jobs:
  harden:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure psql client is installed
        run: |
          if ! command -v psql >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y postgresql-client
          fi

      - name: Run production hardening SQL
        if: ${{ secrets.SUPABASE_DB_URL }}
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          echo "Running production hardening script against Supabase" 
          psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f scripts/harden_supabase.sql

